### ISSUE TITLE
numero uno

### ISSUE THREAD

**Issue by trimanul** [tootiltedboy/Straving-C-days#1]
Для выполнения данной титанической задачи нужно изучить основы гита: что такое репа, коммит, ветка, как клонировать репозитории, как пушить в них коммиты.
![изображение](https://github.com/user-attachments/assets/a097d903-5fca-4677-ba6d-80f588b4d519)

- [x] Склонировать репу в CLion
- [x] Если в репе не будет веток, создать ветку `master` - в дальнейшем это будет наша основная ветка.
- [x] Добавить туда файлик .`gitignore` (изучить что это и зачем)
- [x] Создать файлик README.md (В этом файлике описывается инфа о твоем репозитории) `Contributed by` @morozzov
- [x] Создать отдельную ветку с осмысленным названием
- [x] Добавить туда файлик с какими то уже решенными задачками
- [x] Закоммитить с адекватным сообщением (под адекватным имеется ввиду описать что в коммите сделано, а не просто 1 слово, особо графоманить тоже не надо, но оч короткие коммит меседжи это кринж. кст сообщения пишем на инглише)
- [x] Запушить в репу
- [x] Создать пулл реквест своей ветки в ветку main
- [x] Поставить в reviewer меня и еще кого-то, в assignee себя
- [x] После того, как все ревьюеры аппрувнут ПР смерджить ветку
- [x] Отписать в этот ишью что сделал
- [x] Profit 
- [x] ❤️

**КД: Выходные**

**Comment by trimanul** [comment]
@tootiltedboy

**Comment by de4dlyduck** [comment]
Если не справишься, то -крутки в гашне

**Comment by trimanul** [comment]
Ток ща вспомнил: еще есть оч прикольная утилитка которая доходчиво объясняет как работает гит с графическими примерами:
https://learngitbranching.js.org/?locale=ru_RU

**Comment by pan1caisreal** [comment]
с++ enjoer

**Comment by morozzov** [comment]
- [x] Создать и оформить файл README.md

**Comment by trimanul** [comment]
Вери гуд вери найс, задачу закрываем
