### ISSUE TITLE
numer sinco

### ISSUE THREAD

**Issue by trimanul** [tootiltedboy/Straving-C-days#4]
Вектора - для душнил, идем по базе
(в тему динамических массивов также включаются поинтеры, и все приколы C++ с памятью, так что если не знаем их, то идем учить что такое указатель и референс)
- [x] Изучить что такое статические массивы в C и C++ (как оно лежит в памяти, как им пользоваться)

3 опциональных гига-задачи, для решения которых по сути надо знать массивы и лупы:
1. Write a C++ program to find the largest element of a given array of integers.

2. Write a C++ program to find the largest three elements in an array.

3. Write a C++ program to find the second largest element in an array of integers.

КД: Среда

**Comment by trimanul** [comment]
@tootiltedboy

**Comment by tootiltedboy** [comment]
Дедлайн не указал

**Comment by trimanul** [comment]
> Дедлайн не указал

а ведь действительно

**Comment by tootiltedboy** [comment]
ну будь ты человеком, на выходных отдыхать надо, давай хоть пн-вт или вт-ср

**Comment by trimanul** [comment]
хорошо хорошо, будет тебе среда

**Comment by tootiltedboy** [comment]
чинайзес
